### ISSUE TITLE
训练时代码如何区分normal_patch/和tumor_patch目录

### ISSUE THREAD

**Issue by Alexander0211** [ilikewind/CAMELYON16#10]
您好，我train前生成了3个Patch目录,分别是：
normal.tif生成的normal_patch/;
tumor.tif生成的tumor_patch/;
tumor.tif生成的non_tumor_patch/;
一起放在/home/zbs/camelyon16_data/training/目录下，
我在cnn.json中给出的  "data_path_train": "/home/zbs/camelyon16_data/training/",
我的问题是：train.py代码中是如何区分training/下的不同patch目录的，谢谢。

**Comment by wilmerwang** [comment]
normal_patch + non_tumor_patch组成阴性样本,其中所有的补丁图像应当放入normal文件夹下；tumor_patch是阳性样本，其中所用样本放入tumor文件夹下。然后将tumor文件夹和normal文件夹放进training文件夹
如下：
```
training/
├─normal/
│  └─patch_0001.png
|  └─patch_0002.png
└─tumor/
│  └─patch_0001.png
|  └─patch_0002.png
```
