### ISSUE TITLE
关于train_normal.txt来源

### ISSUE THREAD

**Issue by yangyang117** [ilikewind/CAMELYON16#12]
作者您好，请问train_normal.txt是通过正常切片获取的还是通过Tumor_001_normal.npy这类文件生成的呢？

**Comment by wilmerwang** [comment]
是的，通过Tumor_*_normal.npy  以及  Normal_*_normal.npy 这些正常区域的掩码随机获取的（也就是tumor病理图像的正常区域，和normal病理图像的所有组织区域）。

**Comment by yangyang117** [comment]
谢谢您的回复

**Comment by wilmerwang** [comment]
> 谢谢您的回复

不客气呢
