### ISSUE TITLE
关于代码中的一些理解问题

### ISSUE THREAD

**Issue by yangyang117** [ilikewind/CAMELYON16#13]
您好，通过阅读您的代码，有一些小问题想请教。
1.wsi_classification.py中，使用的是tumor和normal进行分类。但是我看原挑战中的描述为：
First Evaluation: Participants need to provide a single CSV file, with the first column corresponding to the name of the image and the second column containing the probability of that image to contain metastasis.
我理解是要预测是否包含转移，请问为什么直接按照tumor和normal进行分类呢？
2.Evaluation_FROC.py中，ground truth tif文件是怎么获取的呢？
3.热力图是怎么生成的呢？这部分代码请问有没有共享呢？

**Comment by wilmerwang** [comment]
1. 第一个任务就是WSI分类，通过对一个WSI所有补丁图像进行预测并生成该WSI的概率图，然后基于该概率图对这个WSI进行预测分类；
2. ground truth tif 之前官网是有提供了，目前我看了一眼貌似没有了。我可以给你提供一个基本的解决方案,
    1. 安装[ASAP](https://github.com/GeertLitjens/ASAP/releases)
    2. Configure your PYTHONPATH environment variable to contain the /bin directory path.大体就是建立一个PYTHONPATH名字的环境变量，找到你安装ASAP的路径，将路径>>到/bin 这个路径放在PYTHONPATH环境变量中，这样，python就可以自动搜索到这个包了；
    3. 官方demo
```python
import multiresolutionimageinterface as mir
reader = mir.MultiResolutionImageReader()
mr_image = reader.open('camelyon17/centre_0/patient_010_node_4.tif')
annotation_list = mir.AnnotationList()
xml_repository = mir.XmlRepository(annotation_list)
xml_repository.setSource('camelyon17/centre_0/patient_010_node_4.xml')
xml_repository.load()
annotation_mask = mir.AnnotationToMask()
camelyon17_type_mask = True 
 # _0 等就是你自己设置的group，ASAP默认group为Annotation Group *
label_map = {'metastases': 1, 'normal': 2} if camelyon17_type_mask else {'_0': 1, '_1': 1, '_2': 0}
conversion_order = ['metastases', 'normal'] if camelyon17_type_mask else  ['_0', '_1', '_2']
annotation_mask.convert(annotation_list, output_path, mr_image.getDimensions(), mr_image.getSpacing(), label_map, conversion_order)
```

3. 热力图是通过probs_map.py生成的，生成的是一个npy格式文件，通过numpy读取可以显示热图；
