### ISSUE TITLE
关于数据预处理-补丁图像获取的问题

### ISSUE THREAD

**Issue by jijun-cheng** [ilikewind/CAMELYON16#16]
您好，我想请问一下，按照您的说明进行获取补丁图像的第2步，源数据文件及路径都没错，但是运行tumor_mask.py时总报错（第1步，tissue_mask.py可正常运行处理），请问这可能是什么原因造成的，需要怎样处理解决？![image](https://user-images.githubusercontent.com/55268529/91560285-2e416980-e96c-11ea-8b3e-035f60891ec5.png)

**Comment by watchmexiang** [comment]
@chengjijun-sunning 请问您解决了吗，我也遇到了同样的问题

**Comment by niecongchong** [comment]
> @chengjijun-sunning 请问您解决了吗，我也遇到了同样的问题

Hello, I have just started my research on Camelyon17, and I would like to ask you about the GPU memory and time you need to train the whole data set.
Thank you very much!

**Comment by rocketche** [comment]
@chengjijun-sunning @watchmexiang 建议先在python中看一下openslide3.4.1和openslide-python1.1.2是否import不报错。lowlevel.py和openslide密切相关！
