### ISSUE TITLE
热力图生成问题

### ISSUE THREAD

**Issue by cxz123456** [ilikewind/CAMELYON16#19]
兄弟，问个问题，在生成热力图阶段，如果对于测试集的每一个图片的每一个像素都提取patch然后分类patch，那么应该是对这个patch的中心像素有一个0-1之间的值，如果想对每个WSI图像的所有像素都预测，那会花费非常的时间，一个WSI图像大概有10万*10万像素呀，这是怎么解决的呢

**Comment by rocketche** [comment]
我觉得你可能认为一个像素是一个patch，其实一个patch是从WSI中提取的类似于256*256的图片。并且只限于组织区域，并不会很耗时。

**Comment by cxz123456** [comment]
兄弟能留一下你的qq吗，我也是西工大的，有点详细的问题想咨询一下，或者留个邮箱啥的也行
