### ISSUE TITLE
如何生成tumor_train.txt 和 normal_train.txt？

### ISSUE THREAD

**Issue by qzsrh** [ilikewind/CAMELYON16#6]
## 获取补丁数据集
python CAMELYON16/camelyon16/bin/patch_gen.py /WSI_TRAIN/ tumor_train.txt /PATCHES_TUMOR_TRAIN/
python CAMELYON16/camelyon16/bin/patch_gen.py /WSI_TRAIN/ normal_train.txt /PATCHES_NORMAL_TRAIN/
python CAMELYON16/camelyon16/bin/patch_gen.py /WSI_TRAIN/ umor_valid.txt /PATCHES_TUMOR_VALID/
python CAMELYON16/camelyon16/bin/patch_gen.py /WSI_TRAIN/ normal_valid.txt /PATCHES_NORMAL_VALID/

**Comment by xiaobovlog** [comment]
tumor_train.txt 和normal_train.txt 都是第4步中生成的train_spot.txt
Turmor_001_tumor.npy 生成的点就叫tumor_train.txt 
Turmor_001_normal.npy和Normal_001_normal.npy生成的点就叫normal_train.txt

**Comment by GilbertKun** [comment]
有一个问题，我看到代码里，是按第四步得到的点作为中心，如果用到比如Turmor_001_normal.npy，也有可能将tumor有病的掩码部分的一些点包括进来吧？这是不是不太合适，还是我理解错了？
还有一个问题，得到概率图后，把大于零的都变成255，转化成黑白掩膜，这样255的当成肿瘤，是这样理解吗？还是怎么转化？

**Comment by rocketche** [comment]
@ilikewind  您好，有个问题想请教一下，请问 tumor_train.txt和normal_train.txt 与 tumor_valid.txt和normal_valid.txt 的内容是否一样呢？验证集（valid）是测试集的图片吗？他们之间的关系是怎样的呢？谢谢。

**Comment by qzsrh** [comment]
你好,我没有区分训练集和验证集,两者用的都是训练数据。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ilikewind/CAMELYON"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 中午1:00
收件人:&nbsp;"ilikewind/CAMELYON"<CAMELYON@noreply.github.com&gt;;
抄送:&nbsp;"Yee"<3299329141@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ilikewind/CAMELYON] 如何生成tumor_train.txt 和 normal_train.txt？ (#6)





 
@ilikewind  您好，有个问题想请教一下，请问 tumor_train.txt和normal_train.txt 与 tumor_valid.txt和normal_valid.txt 的内容是否一样呢？如何区分训练集和验证集呢？有比较明确的划分吗？谢谢。

**Comment by wilmerwang** [comment]
> 有一个问题，我看到代码里，是按第四步得到的点作为中心，如果用到比如Turmor_001_normal.npy，也有可能将tumor有病的掩码部分的一些点包括进来吧？这是不是不太合适，还是我理解错了？
> 还有一个问题，得到概率图后，把大于零的都变成255，转化成黑白掩膜，这样255的当成肿瘤，是这样理解吗？还是怎么转化？

1. 会有这种可能，但是不影响的；
2. 得到的概率图是为了提取WSI的特征，这个项目中有两个阈值（0.9和0.5）
![image](https://user-images.githubusercontent.com/35020700/102193922-a326b800-3ef7-11eb-81ff-cde8ec21ea24.png)

**Comment by wilmerwang** [comment]
> @ilikewind 您好，有个问题想请教一下，请问 tumor_train.txt和normal_train.txt 与 tumor_valid.txt和normal_valid.txt 的内容是否一样呢？验证集（valid）是测试集的图片吗？他们之间的关系是怎样的呢？谢谢。

training data 划分为训练集和验证集，训练集训练模型，验证集挑选最优模型；test data就是测试集，在构建模型，训练模型的过程中不参与，仅仅起到模型完成后的测试性能的作用；
