### ISSUE TITLE
文件路径怎样设置？

### ISSUE THREAD

**Issue by XIBEI-95** [ilikewind/CAMELYON16#7]
**您好，我想问下文件的路径怎样设置？**
parser.add_argument('xml_path', default=None, metavar='XML_PATH', type=str,
                    help='Path to the input Camelyon16 xml annotation')
我发现只能将default值改为某个文件的路径，比如../Camelyon16/training/lesion_annotations/tumor_001.xml,只能一个一个图片进行处理？请问应该怎样设置可以自动顺序处理同一文件目录下所有特定类型的文件？

**Comment by ilikewind** [comment]
你写个循环遍历文件夹脚本就好了

**Comment by wilmerwang** [comment]
> **您好，我想问下文件的路径怎样设置？**
> parser.add_argument('xml_path', default=None, metavar='XML_PATH', type=str,
> help='Path to the input Camelyon16 xml annotation')
> 我发现只能将default值改为某个文件的路径，比如../Camelyon16/training/lesion_annotations/tumor_001.xml,只能一个一个图片进行处理？请问应该怎样设置可以自动顺序处理同一文件目录下所有特定类型的文件？

你写个文件夹循环遍历脚本就好了

**Comment by XIBEI-95** [comment]
> > **您好，我想问下文件的路径怎样设置？**
> > parser.add_argument('xml_path', default=None, metavar='XML_PATH', type=str,
> > help='Path to the input Camelyon16 xml annotation')
> > 我发现只能将default值改为某个文件的路径，比如../Camelyon16/training/lesion_annotations/tumor_001.xml,只能一个一个图片进行处理？请问应该怎样设置可以自动顺序处理同一文件目录下所有特定类型的文件？
> 
> 你写个文件夹循环遍历脚本就好了

好的，谢谢~
